name: hexview
description: Pretty print byte array as hexadecimal view
version: 2.0.1
homepage: https://github.com/tejainece/hexview.dart

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.14.0
  pedantic:
