name: hexview
description: Pretty print byte array as hexadecimal view
version: 0.0.1
homepage: https://github.com/tejainece/hexview.dart
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
