name: ninja_hex
description: Dart library to encode, decode and pretty print hex string
version: 1.0.0
homepage: https://github.com/ninja-dart/hex

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.14.0
  pedantic:
